### ISSUE TITLE
Optimise for iPad Pro

### ISSUE THREAD

**Issue by alanzchen** [gonativeio/gonative-ios#1]
On iPad Pro it is scaled.

**Comment by jgstew** [comment]
Can you include a screenshot example?

**Comment by cdiscrete** [comment]
I don't have an iPad Pro now, but you can reproduce this problem in a Xcode Simulator.

**Comment by cdiscrete** [comment]
To clarify, by "scale" I mean that it is directly scaled regardless the DPI. It looks like a low-resolution screen scaled to a retina display.

**Comment by snyderj** [comment]
In latest Xcode, you may try including Launch Storyboard to support iPad Pro in native resolution.
