### ISSUE TITLE
Hide iPhone home indicator

### ISSUE THREAD

**Issue by ofrias** [gonativeio/gonative-ios#10]
Could you please implement prefersHomeIndicatorAutoHidden to hide the iPhone home indicator bar?

https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden

**Comment by snyderj** [comment]
Hi @ofrias - Thanks for this suggestion. For now you may make local modification to the iOS source to modify this default value, but we will look into changing it directly in our iOS source code as well. Thanks!

**Comment by ofrias** [comment]
Which is the local modification that I have to do?

**Comment by weiyin** [comment]
Hi, Oscar.

We have just deployed a new version to support this feature. Go to your app's manage page and open Import / Export. Under "styling":{ add this line:

"iosAutoHideHomeIndicator": true,

Click "Update my app!" and give it a try.
