### ISSUE TITLE
'OneSignal/OneSignal.h' file not found

### ISSUE THREAD

**Issue by rifkytech** [gonativeio/gonative-ios#11]
how to fix 'OneSignal/OneSignal.h' file not found' when to build the app?

**Comment by kerrybad** [comment]
any feed back on how to sort this issue out?

**Comment by weiyin** [comment]
Please make sure you are using the latest version of Xcode, and that you open the GoNativeIOS workspace, not the project.

**Comment by kerrybad** [comment]
thank you i will do the updates #HoldingThumps
