### ISSUE TITLE
Can't build the project from a command line

### ISSUE THREAD

**Issue by dillorscroft** [gonativeio/gonative-ios#12]
I'm not a native iOS developer but I'd like to be able to build the application from a command line so I can do the same  in our CI/CD pipeline.  

I'm constantly getting errors like ld: framework not found Pods_OneSignalNotificationServiceExtension and clang: error: linker command failed with exit code 1 

I've zero idea how to ersolve this and google is not being helpful.

Should the application be easy enough to compile from command line or am I being a complete noob?    It does work in Xcode.

**Comment by weiyin** [comment]
Can you make sure you are building the workspace? Here is an example command that creates a simulator build:

`xcodebuild -workspace GoNativeIOS.xcworkspace -scheme GonativeIO -sdk iphonesimulator -configuration Release -derivedDataPath ./build`
