### ISSUE TITLE
Spacing below modals

### ISSUE THREAD

**Issue by maxsalven** [gonativeio/gonative-ios#18]
https://github.com/gonativeio/gonative-ios/commit/6ef40dbd561744300c696ced071593403dac56ec introduced a breaking change on iOS. Full screen modals are now no longer full screen, there is a gap below them which shows the underlying element. Presumably the intention was to make space for the bottom bar, but given it breaks modals, is there an easy way to toggle this off?

**Comment by kgifford** [comment]
Thanks for this. We've deployed a fix in https://github.com/gonativeio/gonative-ios/commit/89131ef7de005d6105e9f56dded7221fd317a0b1
