### ISSUE TITLE
iOS native notifications show up with a 25 second delay when the app is open

### ISSUE THREAD

**Issue by maxsalven** [gonativeio/gonative-ios#19]
Please see https://documentation.onesignal.com/docs/30-api-reference-ios#setnotificationwillshowinforegroundhandler-method

The `notifWillShowInForegroundHandler` method does not call `completed(nil)` which means the notification will show up in your app after 25 seconds.

**Comment by kgifford** [comment]
Thank you for submitting, has been fixed in https://github.com/gonativeio/gonative-ios/commit/27ec01a3b33823ebc841c145a0c07e92e9a30476
