### ISSUE TITLE
Slide left to right to go back instead of opening the menu

### ISSUE THREAD

**Issue by kintaro1981** [gonativeio/gonative-ios#3]
About the back gesture GoNative.io said that they can justify the development to implement this once 5 new licenses are bought asking for this request.

I would like to have this feature optional, so licensee can choose if activate it or have the actual back button or nothing.

Please, if you are interested in this feature write here so we can count us and get the "slide to go back" feature developed.

(I think I'm going to buy at least 1 license in a couple of monthes)

Please if you are interested leave a message here.

**Comment by Cherry** [comment]
We'd also be interested to see this feature developed. We're looking at purchasing a license in the next few weeks, and would love to see the implementation of  iOS back/forward swipe gestures, just as it works in Safari.

**Comment by blyleven** [comment]
+1 :)

**Comment by snyderj** [comment]
Closing issue. Please email support if you would like to revisit this development.
