### ISSUE TITLE
Navigation Menu Links

### ISSUE THREAD

**Issue by MRZMUH001** [gonativeio/gonative-ios#7]
Hi!

I have been attempting a solution (to submit a PR eventually) to have the navigation menu bar on the right side but have ran into a slight hiccup.

The solution allows for having the back button on the left, and the menu button with the menu (frostedview) sliding from the right side. This allows us to have the navigation menu on all pages along with the back button for pages with urlLevel > 1.

But the links in the navigation menu do not seem to be working for certain cases (on pages with urlLevel > 1).

Basically, links with urlLevel less than the current urlLevel, and any javascript links do not work. Links with urlLevel > current urlLevel do work.

Hoping you can see what I was doing wrong...

The steps I took (brief explanation):
1. Add a property in config.json to specify direction of the navigation menu
2. Use this property in appConfig.h

In LeanRootViewController.m
3. Set self.direction property of the frostedviewcontroller based on the appconfig to slide the menu from right.

In LeanWebViewController.m
4. Use the direction property to either place the `self.navButton` in left or right BarButtonItems.
5. Improve logic in the setSidebarEnabled function by accounting for placement above. If left, only enable it on rootwebview, otherwise only if we are showing the navigation menu.

The problem starts in the logic where we load the request, based on the structured nav level.
```
NSInteger newLevel = [LEANWebViewController urlLevelForUrl:url];

if (self.urlLevel >= 0 && newLevel >= 0) {
        if (newLevel > self.urlLevel) {
            // push a new controller
        }
        else if (newLevel < self.urlLevel) {
            // find controller on top of the first controller with a lower-numbered level
        }
```

The logic above to load the request is not met, because for some reason newLevel = self.urlLevel.

Is there something else I need to do?

**Comment by MRZMUH001** [comment]
![screen shot 2018-01-19 at 10 02 55](https://user-images.githubusercontent.com/5204414/35140459-fbcd18c4-fcff-11e7-9427-8d81d8e75893.png)
![screen shot 2018-01-19 at 10 03 02](https://user-images.githubusercontent.com/5204414/35140461-fd6d046e-fcff-11e7-8830-69c4512f7dcd.png)

some screenshots on page which is level 3..
Links not working: Home is level 1, Sien in Afrikaans and Login are JS links, Favourites is level 1.
Links working: Contact is Level 4.

Note all these links work on level 1 page.

**Comment by weiyin** [comment]
Hi,

The navigation levels should not be affected by the changes you indicate. Can you verify that your navigation level config works on the unmodified source code? I suspect it is simply an issue with your regexes.
