### ISSUE TITLE
Weird looking webview on load

### ISSUE THREAD

**Issue by blyleven** [gonativeio/gonative-ios#8]
Hi all! 

I'm currently trying out GoNative to see if it will fit my needs and it looks promising so far. There is one thing I noticed, which I hope could be fixed. When starting the app, right after the launch screen and before the webview loads the website, I see something weird. I've attached an image. Anybody got a solution for this?

![img_0836](https://user-images.githubusercontent.com/4598259/35216677-a9260b38-ff68-11e7-94a7-0a298e098b18.PNG)

**Comment by snyderj** [comment]
Hi, please make sure your website loads in Mobile Safari, and also passes SSL test at https://gonativeio.groovehq.com/knowledge_base/topics/blank-page-or-ssl-connection-errors?from_search=true. If continuing issues, please contact support.
